import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Design system tokens (from design/paper_ledger)
        "surface-bright": "#f8f9fb",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f1f4f7",
        "surface-container": "#eaeef2",
        "surface-container-high": "#e2e9ee",
        "surface-container-highest": "#dbe4ea",
        "surface-dim": "#d1dce2",
        "surface-variant": "#dbe4ea",
        "surface-tint": "#5e5e5e",
        "surface": "#f8f9fb",
        "background": "#f8f9fb",
        "inverse-surface": "#0c0f10",
        "on-surface": "#2b3438",
        "on-surface-variant": "#586065",
        "on-background": "#2b3438",
        "inverse-on-surface": "#9b9d9f",
        "primary": "#5e5e5e",
        "primary-dim": "#525252",
        "primary-fixed": "#e2e2e2",
        "primary-fixed-dim": "#d4d4d4",
        "primary-container": "#e2e2e2",
        "on-primary": "#f8f8ff",
        "on-primary-fixed": "#3f3f3f",
        "on-primary-fixed-variant": "#5b5b5b",
        "on-primary-container": "#525252",
        "inverse-primary": "#ffffff",
        "secondary": "#556071",
        "secondary-dim": "#4a5464",
        "secondary-container": "#d9e3f7",
        "secondary-fixed": "#d9e3f7",
        "secondary-fixed-dim": "#cbd5e9",
        "on-secondary": "#f8f8ff",
        "on-secondary-container": "#485263",
        "on-secondary-fixed": "#364050",
        "on-secondary-fixed-variant": "#525c6d",
        "tertiary": "#585f6d",
        "tertiary-dim": "#4c5361",
        "tertiary-container": "#dfe5f6",
        "tertiary-fixed": "#dfe5f6",
        "tertiary-fixed-dim": "#d1d7e7",
        "on-tertiary": "#f8f8ff",
        "on-tertiary-container": "#4d5461",
        "on-tertiary-fixed": "#3a414e",
        "on-tertiary-fixed-variant": "#565e6b",
        "outline": "#737c81",
        "outline-variant": "#abb3b9",
        "error": "#9e3f4e",
        "error-dim": "#4f0116",
        "error-container": "#ff8b9a",
        "on-error": "#fff7f7",
        "on-error-container": "#782232",
        // Programa-inspired accent
        "lime": "#CAFF33",
        "lime-dark": "#a8d900",
        // Keep utility aliases
        "warning": "#92400E",
        "warning-bg": "#FEF3C7",
        "warning-border": "#FDE68A",
      },
      fontFamily: {
        sans: ["'DM Sans'", "Inter", "sans-serif"],
        headline: ["'DM Sans'", "sans-serif"],
        body: ["'DM Sans'", "sans-serif"],
        label: ["'DM Sans'", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        sm: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      boxShadow: {
        vellum: "0 24px 48px -12px rgba(43, 52, 56, 0.04)",
      },
    },
  },
  plugins: [],
};

export default config;
